server:
  port: 8081

spring:
  application:
    name: employee-service


  datasource:
    url: jdbc:mysql://localhost:3306/employeeMgmt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # ✅ Updated dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # ✅ Use container name
  instance:
    prefer-ip-address: true
    hostname: ${HOST_IP:127.0.0.1}

logging:
  level:
    feign.client: DEBUG
